config/routes.rb
Beesneeds::Application.routes.draw do
  resources :photos do
    collection do
      get :recentactivity
      get :adminmiscphotos
      get :adminreportphotos
    end
  end
  get "pages/home"
  get "pages/stat"
  get "pages/info"
  devise_for :users
  resources :reports

  resources :blocks
  get '/adminmiscphotos', :to => 'photos#adminmiscphotos' 
  get '/adminreportphotos', :to => 'photos#adminreportphotos'

  root :to => redirect('/pages/home')

  

end

app/models/block.rb
# Block model
class Block < ActiveRecord::Base
	has_many :reports
	belongs_to :user
	validates_uniqueness_of :block_number
	validates_uniqueness_of :nickname
	has_one :info
	validates :nickname, :presence => true
	validates_format_of :block_number, with: /((\A153...\z)|(\A555555\z)|(\A159...\z))/, :message => "invalid--please try again and note that you may not register blocks from previous seasons of The Bees' Needs. If you're trying to report an observation on a bee block from 2013 or 2014, please use the Submit Photo option." 

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << ["Block Number", "First Name", "Last Name", "Email"]
			all.each do |block|
				csv << [block.block_number] + [block.user.first_name] + [block.user.last_name] + [block.user.email]
			end
		end
	end
end

app/controllers/blocks_controller.rb
# Handles HTTP requests for Blocks
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  # GET /blocks.json
  def index
    if current_user.admin?
      @blocks = Block.all

      @user_ids = Array.new
      @users = Array.new

      for block in @blocks
        @user_ids << block.user_id
      end

      @users = User.where(:id => @user_ids)
    else
      @blocks = Block.where(:user_id => current_user.id)
    end
    
    respond_to do |format|
      format.html
      format.csv { send_data @blocks.to_csv }
      format.xls { send_data @blocks.to_csv(col_sep: "\t") }
    end

  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)
    @block.user_id = current_user.id

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully registered.' }
        format.json { render action: 'show', status: :created, location: @block }
      else
        format.html { render action: 'new' }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:block_number, :user_id, :nickname)
    end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :block_number, "Please enter your six-digit bee block number:" %>
    <%= f.text_field :block_number %>
  </div>

  <div class="field">
    <%= f.label :nickname, "To make it easier to keep track of your bee block, add a nickname for your block here:" %>
    <%= f.text_field :nickname%>
  </div> <br/>

  <div class="actions">
    <%= f.submit "Register Block", class:"btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<% if current_user.admin? %>
    <h1>Admin Bee Blocks List - (<%=(@blocks.count)%>) </h1>
      <table class = "table table-striped table-hover">
        <thead>
        <tr>
          <th>Block Number</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Block Nickname</th>
          <th>Edit Block</th>
          <th>Delete Block</th>
        </tr>
        </thead>
        
        <tbody>
        <% @blocks.each do |block| %>
            <tr>
              <td><%= block.block_number %></td>
              <td><%= block.user.first_name %></td>
              <td><%= block.user.last_name %></td>
              <td><%= block.user.email %></td>
              <td><%= block.nickname %></td>
              <td><%= link_to 'Edit ', edit_block_path(block) %></td>
              <td><%= link_to 'Delete', block, method: :delete, data: { confirm: 'Do you wish to delete this block?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>
      <div class="btn-group btn-group-justified">
        
          <%= link_to 'Register a Bee Block', new_block_path, method: :get, class: "btn btn-large btn-primary" %>
        
          <%= link_to 'Report Activity', reports_path, class: "btn btn-large btn-primary" %>
        
        
          <%= link_to 'Export as CSV', blocks_path(format: "csv") , class: "btn btn-large btn-primary"%>
        
          <%= link_to 'Export to Excel', blocks_path(format: "xls") , class: "btn btn-large btn-primary"%>
        
      </div>


      <br>

<% else %>

<h1>Your Bee Blocks - (<%=(@blocks.count)%>) </h1>


<div class = "center hero-unit">
<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Block Number</th>
      <th>Block Nickname</th>
      <th>Edit Block</th>
      <th>Delete Block</th>
    </tr>
  </thead>



  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.block_number %></td>
        <td><%= block.nickname %></td>
        
        <td><%= link_to 'Edit ', edit_block_path(block) %></td>
        <td><%= link_to 'Delete', block, method: :delete, data: { confirm: 'Do you wish to delete this block?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <div class="btn-group btn-group-justified">
    <div class="btn-group">
      <%= link_to 'Register a Bee Block', new_block_path, method: :get, class: "btn btn-large btn-primary" %>
    </div>
    <div class="btn-group">
      <%= link_to 'Report Activity', reports_path, class: "btn btn-large btn-primary" %>
    </div>
    <div class="btn-group">
      <%= link_to "Basic Info about You and Your Bee Block Survey",  "https://cuboulder.qualtrics.com/jfe/form/SV_3rWpaek9lYzlvkV", class: "btn btn-large btn-primary" %>
    </div>
  </div>


<br>

</div>
<% end %>

app/views/blocks/new.html.erb
<h1>Register Your Bee Block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p>
  <strong>Block number:</strong>
  <%= @block.block_number %>
</p>

<p>
  <strong>Block nickname:</strong>
  <%= @block.nickname %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Next', blocks_path %>