config/routes.rb
Beesneeds::Application.routes.draw do
  resources :photos do
    collection do
      get :recentactivity
      get :adminmiscphotos
      get :adminreportphotos
    end
  end
  get "pages/home"
  get "pages/stat"
  get "pages/info"
  devise_for :users
  resources :reports

  resources :blocks
  get '/adminmiscphotos', :to => 'photos#adminmiscphotos' 
  get '/adminreportphotos', :to => 'photos#adminreportphotos'

  root :to => redirect('/pages/home')

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, MiscPhotoUploader
  belongs_to :user
  validates :image, :presence => true
  validates :image_subject, :presence => true
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @report_photos = Array.new
    if current_user.admin? == false
      @user = current_user.id
      @photos = Photo.where(['user_id = ?', @user]).paginate(:page => params[:photo_page], :per_page => 5)
      @blocks = Block.where(:user_id => current_user.id)
      @user_reports = Array.new
      for block in @blocks
        @user_reports << block.block_number
      end
      @report_photos = Report.where(:block_number => @user_reports)
      @report_photos = @report_photos.where("image_subject is NOT NULL and image_subject != ''").paginate(:page => params[:report_photo_page], :per_page => 5)
    else
      @photos = Photo.all
      @photos = Photo.paginate(:page => params[:photo_page], :per_page => 5)
      @report_photos = Report.where("image_subject is NOT NULL and image_subject != ''").paginate(:page => params[:report_photo_page], :per_page => 5)
    end
  end

  def adminmiscphotos
    @photos = Photo.all
    @photos = Photo.paginate(:page => params[:photo_page], :per_page => 5)
  end

  def adminreportphotos
    @report_photos = Report.where("image_subject is NOT NULL and image_subject != ''").paginate(:page => params[:report_photo_page], :per_page => 5)
  end

  def recentactivity
    @photos = Photo.all(:order => "date DESC", :limit => 5)
  end


  # GET /photos/1
  # GET /photos/1.json
  def show

  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = current_user.photos.build(photo_params)
    @photo.block_number =
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:comment, :date, :image_subject, :image, :block_number)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_editform.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
        <div id="error_explanation" xmlns="http://www.w3.org/1999/html">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "hero-unit">
    <div class="field">
      <%= f.label 'Edit block:' %>
      <%= f.collection_select :block_number, Block.where(:user_id => current_user.id), :block_number, :block_number, :prompt => false  %>
    </div>
    
    <div class = "field">
        <%= f.label "Edit subject:" %>
        <%= f.select :image_subject, [[''],['Nest plug'], ['Insect at my bee block'], ['Insect not at my bee block'], ['Whole Block'], ['Miscellaneous']] %><br />
    </div>
    <div class = "field">
      <%= f.label "Change your photo (Leave blank if you don't want to change):" %>
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%= f.label 'Edit observation date:' %>
      <%= f.date_select :date, :class => "datepicker" %>
    </div><br/>

    <div class = "field">
        <%= f.label 'Edit Comment:' %>
        <%= f.text_area :comment %>
    </div><br/>




    <div class="field">
      <%= f.submit "Update Photo", class:"center btn btn-large btn-primary" %>
    </div>

  </div>
<% end %>

app/views/photos/_form.html.erb
<div class="center alert alert-info"><h4>Please use this page to upload photos that are not associated with a particular data record. Photos associated with data should be uploaded on the Data Entry form, along with information on the nest plug/activity report</h4></div>  <br/>

<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
        <div id="error_explanation" xmlns="http://www.w3.org/1999/html">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





  <div class = "hero-unit">
    <div class="field">   
      <%= f.label 'Which block is this report for?' %>
      <%= f.collection_select :block_number, Block.where(:user_id => current_user.id), :block_number, :nickname, :prompt => false, :include_blank => true %>
    </div>
    <div class = "field">
        <%= f.label "Subject of the photo you are uploading:" %>
        <%= f.select :image_subject, [[''],['Nest plug'], ['Insect at my bee block'], ['Insect not at my bee block'], ['Whole Block'], ['Miscellaneous']] %><br />
    </div>
    
    <div class = "field">
      <%= f.label "Select your photo:" %>
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%= f.label 'When did you make this observation?' %>
      <%= f.date_select :date, :class => "datepicker" %>
    </div><br/>

    <div class = "field">
        <h3><small style="color:black">Please tell us about the photo that you’re submitting. If you have already submitted a photo of your nest plug along with a data record for that cavity, but wish to upload additional photos, you may do that here. Please make a note of that  in this comment field.</small></h3>
        <%= f.text_area :comment%>
    </div><br/>




    <div class="field">
      <%= f.submit "Upload Photo", class:"center btn btn-large btn-primary" %>
    </div>

  </div>
<% end %>

app/views/photos/adminmiscphotos.html.erb
<% if current_user.admin? == true %>
        <h1>Admin - Misc Photos</h1>
        <table class="center table table-striped table-hover">
          <thead>
          <tr>
            <th>Image</th>
            <th>Subject</th>
            <th>Bee Block Number</th>
            <th>Comment</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @photos.each do |photo| %>
              <tr>
                <td><%= image_tag(photo.image_url, :width => 100) if photo.image.present? %></td>
                <td><%= photo.image_subject %></td>
                <td><%= photo.block_number %></td>
                <td><%= photo.comment %></td>
                <td><%= photo.user.first_name %></td>
                <td><%= photo.user.last_name %></td>
                <td><%= photo.user.email %></td>
                <td><%= link_to 'Show', photo %></td>
                <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
                <td><%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <br>
        <div class="center"><%= will_paginate @photos, :param_name => 'photo_page' %></div>
<% end %> 

app/views/photos/adminreportphotos.html.erb
 <h1>Admin - Report Photos</h1>
        <div class="center"> Note: To delete these photos, please go to your <a href='/reports'>reports page</a></div>
        <br/>
        <table class="center table table-striped table-hover">
          <thead>
          <tr>
            <th>Image</th>
            <th>Subject</th>
            <th>Comment</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @report_photos.each do |photo| %>
              <tr>
                <td><%= image_tag(photo.image_url, :width => 100) if photo.image.present? %></td>
                <td><%= photo.image_subject %></td>
                <td><%= photo.comment %></td>
                <td><%= photo.block.user.first_name %></td>
                <td><%= photo.block.user.last_name %></td>
                <td><%= photo.block.user.email %></td>
                <td><%= link_to 'Show', photo %></td>
                <td><%= link_to 'Edit', edit_report_path(photo) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
         <div class="center"><%= will_paginate @report_photos, :param_name => 'report_photo_page' %></div>
        <br> <br/>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'editform' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<% if @photos.count == 0 and @report_photos.count == 0 %>
    <h1>Gallery</h1>
    <div class="center hero-unit">
      <p>Add some photos!</p>
      <%= link_to 'Report Data', new_report_path , class: "btn btn-large btn-default"%>
      <%= link_to 'Upload Misc Image', new_photo_path, class: "btn btn-large btn-default"%>
    </div>
<% elsif @photos.count > 0 %>
        <h1>Miscellaneous Photos</h1>
        <table class="center table table-striped table-hover">
          <thead>
          <tr>
            <th>Image</th>
            <th>Subject</th>
            <th>Bee Block Number</th>
            <th>Comment</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @photos.each do |photo| %>
              <tr>
                <td><%= image_tag(photo.image_url, :width => 100) if photo.image.present? %></td>
                <td><%= photo.image_subject %></td>
                <td><%= photo.block_number %></td>
                <td><%= photo.comment %></td>
                <td><%= link_to 'Show', photo %></td>
                <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
                <td><%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <br>
        <div class="center"><%= will_paginate @photos, :param_name => 'photo_page' %></div>
<% end %>

<% if @report_photos.count == 0 %>
<% else %>


        <h1>Photos from Reports</h1>

        <div class="center"> Note: To delete these photos, please go to your <a href='/reports'>reports page</a></div>
        <br/>
        <table class="center table table-striped table-hover">
          <thead>
          <tr>
            <th>Image</th>
            <th>Subject</th>
            <th>Comment</th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @report_photos.each do |photo| %>
              <tr>
                <td><%= image_tag(photo.image_url, :width => 100) if photo.image.present? %></td>
                <td><%= photo.image_subject %></td>
                <td><%= photo.comment %></td>
                <td><%= link_to 'Show', photo %></td>
                <td><%= link_to 'Edit', edit_report_path(photo) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <br> <br/>
    


<% end %>
<div class="center"><%= will_paginate @report_photos, :param_name => 'report_photo_page'%></div>

<% if @photos.count > 0 or @report_photos.count > 0 %>
<div><%= link_to 'New Photo', new_photo_path, class:"btn btn-large btn-primary" %></div>
<% end %>

app/views/photos/new.html.erb
<h1>Upload Photos</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/recentactivity.html.erb
<h1>Recent Photo Uploads</h1>
    <table class="center table table-striped table-hover">
      <thead>
      <tr>
        <th>Image</th>
        <th>Date</th>
        <th>Bee Block Number</th>
        <th>Comment</th>
      </tr>
      </thead>

      <tbody>
      <% @photos.each do |photo| %>
          <tr>
            <td><%= image_tag(photo.image_url, :width => 500) if photo.image.present? %></td>
            <td><%= photo.date %></td>
            <td><%= photo.block_number %></td>
            <td><%= photo.comment %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Photo:</strong>
  <%= image_tag(@photo.image, :width => 600) %>
</p>


<p>
  <strong>Subject:</strong>
  <%= @photo.image_subject %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @photo.comment %>
</p>


<div class="center btn-group btn-group-xs">
<%= link_to 'Gallery', photos_path, class:"btn btn-large btn-primary"%>
<%= link_to 'Edit', edit_photo_path(@photo), class:"btn btn-large btn-primary" %>
<%= link_to 'Back', photos_path, class:"btn btn-large btn-primary" %>
</div>